version: '3.8'

services:
  db:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  backend:
    build:
      context: .
    container_name: click_app

    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  clickhouse_data: